jobs:

# runCI job that builds and pushes artifact
  - name: ruby-blog_runCI
    type: runCI
    steps:
      - OUT: rubyblog-image
    flags:
      - rubyBlog
  
# # Generate manifest
#   - name: rubyblog-manifest
#     type: manifest
#     steps:
#       - IN: rubyblog-img
#       - IN: rubyblog-img-options-test
#       - TASK: managed
#     flags:
#       - rubyBlog

# Deploy to TEST environment
  - name: rubyblog-deploy-test
    type: runSh
    steps:
      - IN: rubyblog-image
      - IN: rubyblog-options-test
      - IN: rubyblog-ecr-config
      - IN: rubyblog-ssh
      - IN: rubyblog-params-test
      - TASK: 
        - script: declare -a VMS && export VMS
        - script: VMS=(34.234.225.35)
        - script: "export DOCKER_LOGIN=$(aws ecr get-login)"
        - script: export IMAGE=${RUBYBLOGIMAGE_SOURCENAME}:${RUBYBLOGIMAGE_VERSIONNAME}
        - script: |
            for n in $VMS; do
              ssh -i $RUBYBLOGSSH_KEYPATH ec2-user@${n} bash -c "'
                $DOCKER_LOGIN
                docker ps
                docker stop rubyapp || true && docker rm rubyapp || true
                docker run -d --name "rubyapp" -l rubyapp:mysql -p 80:3000 -e RAILS_ENV=development $IMAGE
                docker ps
              '"
            done
    flags:
      - rubyBlog
