jobs:

# runCI job that builds and pushes artifact
  - name: ruby-blog_runCI
    type: runCI
    steps:
      - OUT: rubyblog-img-vm
    flags:
      - rubyBlog
  
# Generate manifest
  - name: rubyblog-manifest-vm
    type: manifest
    steps:
      - IN: rubyblog-img-vm
      - IN: rubyblog-img-options-vm-test
      - TASK: managed
    flags:
      - rubyBlog

# Deploy to TEST environment
  - name: rubyblog-deploy-vm-test
    type: runSh
    steps:
      - IN: rubyblog-manifest-vm
      - IN: rubyblog-ssh
      # - IN: rubyblog-cluster-vm-test
      - IN: rubyblog-params-vm-test
      - TASK: 
        - script: declare -a VMS && export VMS && VMS[0]=34.234.225.35
        - script: ECR_PASSWORD=$RUBYBLOGMANIFESTVM_INTEGRATION_AWS_SECRET_ACCESS_KEY
        - script: |
            for n in $VMS; do
              ssh -i $RUBYBLOGSSH_KEYPATH ec2-user@${n} bash -c "'
                docker stop rubyapp || true && docker rm rubyapp || true
                docker login -u ttrahan -p $ECR_PASSWORD -e none https:679404489841.dkr.ecr.us-east-1.amazonaws.com
                docker run --name "rubyapp" 679404489841.dkr.ecr.us-east-1.amazonaws.com/ruby-demo:master.15
              '"
            done
    flags:
      - rubyBlog
